CREATE TABLE enem2011 (
    NU_INSCRICAO BIGINT UNSIGNED PRIMARY KEY,
    ESCOLARIDADE_PAI CHAR,
    ESCOLARIDADE_MAE CHAR,
    RENDA_FAMILIAR CHAR,
    TIPO_ESCOLA CHAR,
    IDADE TINYINT UNSIGNED,
    TP_SEXO TINYINT UNSIGNED,
    COD_MUNICIPIO_INSC MEDIUMINT UNSIGNED,
    ST_CONCLUSAO TINYINT UNSIGNED,
    TP_ESTADO_CIVIL TINYINT UNSIGNED,
    TP_COR_RACA TINYINT UNSIGNED,
    NU_NT_CN FLOAT,
    NU_NT_CH FLOAT,
    NU_NT_LC FLOAT,
    NU_NT_MT FLOAT,
    NU_NOTA_REDACAO FLOAT
);
