CREATE TABLE DADOS (
    NU_INSCRICAO INTEGER PRIMARY KEY,
    IDADE INTEGER,
    TP_SEXO INTEGER,
    COD_MUNICIPIO_INSC INTEGER,
    ST_CONCLUSAO INTEGER,
    TP_ESTADO_CIVIL INTEGER,
    TP_COR_RACA INTEGER,
    NU_NT_CN REAL,
    NU_NT_CH REAL,
    NU_NT_LC REAL,
    NU_NT_MT REAL,
    NU_NOTA_REDACAO REAL
);

CREATE INDEX IDX_MUNICIPIOS ON DADOS(COD_MUNICIPIO_INSC);

CREATE TABLE QUESTIONARIOS (
    NU_INSCRICAO INTEGER PRIMARY KEY,
    ESCOLARIDADE_PAI CHAR,
    ESCOLARIDADE_MAE CHAR,
    RENDA_FAMILIAR CHAR,
    TIPO_ESCOLA CHAR,
    FOREIGN KEY (NU_INSCRICAO) REFERENCES DADOS (NU_INSCRICAO)
);
