DROP TABLE IF EXISTS SUMMARY;

CREATE TABLE SUMMARY (
    COD_MUNICIPIO_INSC MEDIUMINT UNSIGNED,
    IDADE TINYINT UNSIGNED,
    TP_SEXO TINYINT UNSIGNED,
    ST_CONCLUSAO TINYINT UNSIGNED,
    TP_ESTADO_CIVIL TINYINT UNSIGNED,
    TP_COR_RACA TINYINT UNSIGNED,
    ESCOLARIDADE_PAI CHAR,
    ESCOLARIDADE_MAE CHAR,
    RENDA_FAMILIAR CHAR,
    TIPO_ESCOLA CHAR,
    INSCRITOS MEDIUMINT UNSIGNED,
    PRESENTES MEDIUMINT UNSIGNED,
    CN_AVG REAL,
    CH_AVG REAL,
    LC_AVG REAL,
    MT_AVG REAL,
    RE_AVG REAL,
    ME_AVG REAL,
    PRIMARY KEY (
        COD_MUNICIPIO_INSC, IDADE, TP_SEXO, ST_CONCLUSAO, TP_ESTADO_CIVIL, TP_COR_RACA,
        ESCOLARIDADE_PAI, ESCOLARIDADE_MAE, RENDA_FAMILIAR, TIPO_ESCOLA
    )
);

INSERT INTO SUMMARY
SELECT
    COD_MUNICIPIO_INSC, IDADE, TP_SEXO, ST_CONCLUSAO, TP_ESTADO_CIVIL, TP_COR_RACA,
    ESCOLARIDADE_PAI, ESCOLARIDADE_MAE, RENDA_FAMILIAR, TIPO_ESCOLA,
    COUNT(1),
    COUNT(NU_NT_CN+NU_NT_CH+NU_NT_LC+NU_NT_MT+NU_NOTA_REDACAO),
    AVG(NU_NT_CN),
    AVG(NU_NT_CH),
    AVG(NU_NT_LC),
    AVG(NU_NT_MT),
    AVG(NU_NOTA_REDACAO),
    AVG((NU_NT_CN+NU_NT_CH+NU_NT_LC+NU_NT_MT+NU_NOTA_REDACAO)/5)
FROM DADOS D INNER JOIN QUESTIONARIOS Q ON Q.NU_INSCRICAO = D.NU_INSCRICAO
GROUP BY
    COD_MUNICIPIO_INSC, IDADE, TP_SEXO, ST_CONCLUSAO, TP_ESTADO_CIVIL, TP_COR_RACA,
    ESCOLARIDADE_PAI, ESCOLARIDADE_MAE, RENDA_FAMILIAR, TIPO_ESCOLA;
